### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by m4gus88** [m4gus88/USI_RO#1]
- [x] Fix EC consumption of Ranger module deployment
- [x] Fix EC consumption of module swapping
- [x] Ranger CommPack should have an RTAntenna (maybe Comm16 range).
- [x] Modular containers
- [x] RP-1 compatibility
- [ ] RP-1 correct prices (WIP)
- [ ] Maybe add config for stock Drill???
- [x] Malemute Rover
- [x] Exploration pack
- [x] FTT
- [ ] Asteroid Recycling
